-- 入荷記録表（予定+実績統合）
CREATE TABLE INCOMING_RECORD (
    RECORD_ID NUMBER PRIMARY KEY,
    ASN_NO VARCHAR2(20),
    PRODUCT_ID VARCHAR2(20) NOT NULL,
    PLAN_QTY NUMBER,
    ACTUAL_QTY NUMBER,
    ARRIVAL_DATE DATE,
    STATUS VARCHAR2(10) DEFAULT 'PLANNED',
    DISCREPANCY_REASON VARCHAR2(200),
    RECEIVED_AT TIMESTAMP,
    CREATED_AT DATE DEFAULT SYSDATE,
    CONSTRAINT FK_INCOMING_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT_MASTER(PRODUCT_ID),
    CONSTRAINT CHK_INCOMING_STATUS CHECK (STATUS IN ('PLANNED', 'RECEIVED'))
);

-- 在庫表
CREATE TABLE INVENTORY (
    INVENTORY_ID NUMBER PRIMARY KEY,
    PRODUCT_ID VARCHAR2(20) NOT NULL,
    LOCATION_ID VARCHAR2(20) NOT NULL,
    QUANTITY NUMBER DEFAULT 0,
    LAST_UPDATED TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT FK_INVENTORY_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT_MASTER(PRODUCT_ID),
    CONSTRAINT FK_INVENTORY_LOCATION FOREIGN KEY (LOCATION_ID) REFERENCES LOCATION_MASTER(LOCATION_ID)
);

-- 出荷記録表（指示+実績統合）
CREATE TABLE SHIPMENT_RECORD (
    RECORD_ID NUMBER PRIMARY KEY,
    ORDER_NO VARCHAR2(20) NOT NULL,
    CUSTOMER_ID VARCHAR2(20) NOT NULL,
    PRODUCT_ID VARCHAR2(20) NOT NULL,
    ORDER_QTY NUMBER NOT NULL,
    SHIPPED_QTY NUMBER DEFAULT 0,
    SHIPMENT_DATE DATE,
    STATUS VARCHAR2(10) DEFAULT 'PENDING',
    CARRIER VARCHAR2(50),
    TRACKING_NO VARCHAR2(50),
    SHIPPED_AT TIMESTAMP,
    CREATED_AT DATE DEFAULT SYSDATE,
    CONSTRAINT FK_SHIPMENT_CUSTOMER FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER_MASTER(CUSTOMER_ID),
    CONSTRAINT FK_SHIPMENT_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT_MASTER(PRODUCT_ID),
    CONSTRAINT CHK_SHIPMENT_STATUS CHECK (STATUS IN ('PENDING', 'SHIPPED'))
);

-- 棚卸記録表
CREATE TABLE STOCKTAKE_RECORD (
    STOCKTAKE_ID NUMBER PRIMARY KEY,
    PRODUCT_ID VARCHAR2(20) NOT NULL,
    LOCATION_ID VARCHAR2(20) NOT NULL,
    SYSTEM_QTY NUMBER NOT NULL,
    COUNTED_QTY NUMBER NOT NULL,
    DIFFERENCE_QTY NUMBER NOT NULL,
    REASON VARCHAR2(200),
    STOCKTAKE_DATE DATE NOT NULL,
    STATUS VARCHAR2(10) DEFAULT 'PENDING',
    CREATED_AT DATE DEFAULT SYSDATE,
    CONSTRAINT FK_STOCKTAKE_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT_MASTER(PRODUCT_ID),
    CONSTRAINT FK_STOCKTAKE_LOCATION FOREIGN KEY (LOCATION_ID) REFERENCES LOCATION_MASTER(LOCATION_ID),
    CONSTRAINT CHK_STOCKTAKE_STATUS CHECK (STATUS IN ('PENDING', 'COMPLETED'))
);

-- 操作ログ表
CREATE TABLE OPERATION_LOG (
    LOG_ID NUMBER PRIMARY KEY,
    USER_ID VARCHAR2(20),
    OPERATION_TYPE VARCHAR2(50) NOT NULL,
    TABLE_NAME VARCHAR2(50) NOT NULL,
    RECORD_ID VARCHAR2(50),
    OLD_VALUE CLOB,
    NEW_VALUE CLOB,
    OPERATION_TIME TIMESTAMP DEFAULT SYSTIMESTAMP,
    IP_ADDRESS VARCHAR2(20)
);