-- 商品マスタテストデータ
INSERT INTO PRODUCT_MASTER (PRODUCT_ID, PRODUCT_NAME, SPECIFICATION, UNIT, SAFETY_STOCK) VALUES
('P001', '商品A', '規格A', '個', 10);
INSERT INTO PRODUCT_MASTER (PRODUCT_ID, PRODUCT_NAME, SPECIFICATION, UNIT, SAFETY_STOCK) VALUES
('P002', '商品B', '規格B', '個', 20);
INSERT INTO PRODUCT_MASTER (PRODUCT_ID, PRODUCT_NAME, SPECIFICATION, UNIT, SAFETY_STOCK) VALUES
('P003', '商品C', '規格C', '個', 15);

-- 顧客マスタテストデータ
INSERT INTO CUSTOMER_MASTER (CUSTOMER_ID, CUSTOMER_NAME, ADDRESS, PHONE) VALUES
('C001', '顧客A', '東京都渋谷区', '03-1234-5678');
INSERT INTO CUSTOMER_MASTER (CUSTOMER_ID, CUSTOMER_NAME, ADDRESS, PHONE) VALUES
('C002', '顧客B', '大阪府大阪市', '06-1234-5678');
INSERT INTO CUSTOMER_MASTER (CUSTOMER_ID, CUSTOMER_NAME, ADDRESS, PHONE) VALUES
('C003', '顧客C', '愛知県名古屋市', '052-1234-5678');

-- ロケーションマスタテストデータ
INSERT INTO LOCATION_MASTER (LOCATION_ID, WAREHOUSE_CODE, ZONE, RACK, LEVEL_NO, POSITION, MAX_CAPACITY) VALUES
('L001', 'WH01', 'A', 'R001', 'L01', 'P001', 100);
INSERT INTO LOCATION_MASTER (LOCATION_ID, WAREHOUSE_CODE, ZONE, RACK, LEVEL_NO, POSITION, MAX_CAPACITY) VALUES
('L002', 'WH01', 'A', 'R001', 'L01', 'P002', 100);
INSERT INTO LOCATION_MASTER (LOCATION_ID, WAREHOUSE_CODE, ZONE, RACK, LEVEL_NO, POSITION, MAX_CAPACITY) VALUES
('L003', 'WH01', 'A', 'R001', 'L02', 'P001', 100);

-- 初期在庫データ
INSERT INTO INVENTORY (INVENTORY_ID, PRODUCT_ID, LOCATION_ID, QUANTITY) VALUES
(INVENTORY_SEQ.NEXTVAL, 'P001', 'L001', 50);
INSERT INTO INVENTORY (INVENTORY_ID, PRODUCT_ID, LOCATION_ID, QUANTITY) VALUES
(INVENTORY_SEQ.NEXTVAL, 'P002', 'L002', 30);
INSERT INTO INVENTORY (INVENTORY_ID, PRODUCT_ID, LOCATION_ID, QUANTITY) VALUES
(INVENTORY_SEQ.NEXTVAL, 'P003', 'L003', 25);

-- 提交事务
COMMIT;